version: '3.8'

services:
  web:
    build: ../data_modifier
    restart: always
    # REMOVE python manage.py createsuperusersafe from prod docker-compose file
    command: bash -c "python manage.py migrate && 
                      python manage.py createsuperusersafe &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../data_modifier:/usr/src/app/
    ports:
      - 80:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

volumes:
  postgres_data: