name: fic_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  flowder:
    git:
      url: https://github.com/xid-er/flowder.git
  path_provider:
  sn_progress_dialog: ^1.0.3
  flutter_archive:
  flutter_breadcrumb: ^1.0.1
  http:

  flutter_linkify:
  url_launcher:
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/database/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
